jetty-webapp/src/main/config/etc/*           etc/jetty
jetty-policy/src/main/config/etc/*           etc/jetty
jetty-security/src/main/config/etc/*         etc/jetty
jetty-server/src/main/config/etc/*           etc/jetty
jetty-ajp/src/main/config/etc/*              etc/jetty
jetty-annotations/src/main/config/etc/*      etc/jetty
jetty-monitor/src/main/config/etc/*          etc/jetty
jetty-overlay-deployer/src/main/config/etc/* etc/jetty
jetty-rewrite/src/main/config/etc/*          etc/jetty
jetty-plus/src/main/config/etc/*             etc/jetty
jetty-util/src/main/config/etc/*             etc/jetty
jetty-jmx/src/main/config/etc/*              etc/jetty
debian/jetty-shared-webapps.xml              etc/jetty
debian/jetty.conf                            etc/jetty

debian/root-webapp/*                                 var/lib/jetty/webapps/root
test-jetty-webapp/src/main/webapp/jetty_banner.gif   var/lib/jetty/webapps/root
jetty-distribution/src/main/resources/contexts       etc/jetty
jetty-distribution/src/main/resources/resources      usr/share/jetty
jetty-start/target/classes/org/eclipse/jetty/start/start.config etc/jetty

LICENSE-CONTRIBUTOR/cla-*   usr/share/doc/jetty/LICENSES
LICENSE-CONTRIBUTOR/ccla-*  usr/share/doc/jetty/LICENSES
NOTICE.txt                  usr/share/doc/jetty/LICENSES
debian/README.Debian        usr/share/doc/jetty
