#!/bin/sh
set -e

case "$1" in
    configure)
	if ! id jetty > /dev/null 2>&1 ; then
	    adduser --system --home /usr/share/jetty8 --no-create-home \
		--group --disabled-password --shell /bin/false \
		jetty
	fi
	chown -R jetty:adm /var/cache/jetty8 /var/log/jetty8 /var/lib/jetty8
	chmod 750 /var/log/jetty8
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
	echo "$0 called with unknown argument \`$1'" >&2
	exit 1
    ;;
esac

#DEBHELPER#
